bin/rsync-backup: Improve script

diff --git a/bin/rsync-backup b/bin/rsync-backup
--- a/bin/rsync-backup
+++ b/bin/rsync-backup
@@ -3,7 +3,7 @@
 # Perform incremental rsync backup copy of the given labelled directory trees
 # on the given hosts (default local).
 
-set -e
+set -e -u
 shopt -s extglob nullglob lastpipe
 
 usage() {
@@ -17,20 +17,20 @@ main() {
     OPT_DRY_RUN=false
     OPTS_RSYNC=()
     while [[ $# -ne 0 ]]; do
-            case "$1" in
-            -h|-\?|--help) usage; exit 0;;
-            -t) OPT_TEST=true;;
-            -n) OPT_DRY_RUN=true;;
-            -q) OPT_ECHO=false;;
-            -*) OPTS_RSYNC+=("$1");;
-            --) shift; break;;
-            *) break;;
-            esac
-            shift
+        case $1 in
+        -h|-\?|--help) usage; exit 0;;
+        -t) OPT_TEST=true;;
+        -n) OPT_DRY_RUN=true;;
+        -q) OPT_ECHO=false;;
+        -*) OPTS_RSYNC+=("$1");;
+        --) shift; break;;
+        *) break;;
+        esac
+        shift
     done
 
-    LOCAL_HOST_FQ="$(/bin/hostname --fqdn)"
-    [[ -n $LOCAL_HOST_FQ ]] || fatal "cannot determine default hostname"
+    LOCAL_HOST_FQ=$(/bin/hostname --fqdn)
+    [[ $LOCAL_HOST_FQ ]] || fatal "cannot determine default hostname"
 
     [[ $# -ge 2 ]] || fatal_usage "missing argument(s)"
     parse_rsync_endpoint DEST "$1" # sets DESTUSER DESTHOSTFQ DESTHOST DESTDIR
@@ -41,32 +41,33 @@ main() {
     DATE=`/bin/date '+%Y-%m-%d'` || exit 2
     ERR="/tmp/${0##*/}-$$.err"
 
-    PASSWORD=
+    local PASSWORD=
     if [[ $DESTHOSTFQ != $LOCAL_HOST_FQ ]]; then
         read -s -p "Password for $DESTUSER@$DESTHOST:" PASSWORD
         echo >&2
     fi
 
-    SRCPATHS=()
-    for src
-    do
+    local -a SOURCES=()
+    local rsync_output=
+    local src
+    for src; do
         local SRCUSER
         local SRCHOSTFQ
         local SRCHOST
         local SRCDIR
         parse_rsync_endpoint SRC "$src" # sets SRCUSER SRCHOSTFQ SRCHOST SRCDIR
 
-        if [[ $DESTHOSTFQ != $LOCAL_HOST_FQ && $SRCHOSTFQ != $LOCAL_HOST_FQ ]]; then
+        if [[ $DESTHOSTFQ != "$LOCAL_HOST_FQ" && $SRCHOSTFQ != "$LOCAL_HOST_FQ" ]]; then
             fatal_usage "cannot push to remote destination from remote source: $src"
         fi
 
-        local SRCLABEL="$SRCDIR"
+        local SRCLABEL=$SRCDIR
         local SRCPATH
 
         case "$SRCDIR" in
-        ?*=*)   SRCPATH="${SRCDIR#*=}"
-                SRCPATH="${SRCPATH%%+(/)}"
-                SRCLABEL="${SRCDIR%%=*}"
+        ?*=*)   SRCPATH=${SRCDIR#*=}
+                SRCPATH=${SRCPATH%%+(/)}
+                SRCLABEL=${SRCDIR%%=*}
                 ;;
         boot)   SRCPATH=/boot;;
         etc)    SRCPATH=/etc;;
@@ -78,71 +79,69 @@ main() {
         *)      fatal "unsupported label: $SRCDIR";;
         esac
 
-        [[ $SRCHOSTFQ = $LOCAL_HOST_FQ && ! -d $SRCPATH ]] && fatal "missing source directory: $SRCPATH"
+        [[ $SRCHOSTFQ = "$LOCAL_HOST_FQ" && ! -d $SRCPATH ]] && fatal "missing source directory: $SRCPATH"
 
-        LINK_DEST=-
-        if [[ $DESTHOSTFQ = $LOCAL_HOST_FQ ]]; then
+        local LINK_DEST=
+        if [[ $DESTHOSTFQ = "$LOCAL_HOST_FQ" ]]; then
             if pushd "$DESTDIR" >/dev/null 2>/dev/null; then
-                local prev="$(ls -r | sed -n -e "/-$DATE-/d;/^$SRCHOST-$DATEREXP-$SRCLABEL\$/{p;q}")"
-                [[ -d $prev ]] && LINK_DEST="$prev"
+                LINK_DEST=$(ls -r | sed -n -e "/-$DATE-/d;/^$SRCHOST-$DATEREXP-$SRCLABEL\$/{p;q}")
                 popd >/dev/null
             fi
         else
-            local rsync_output
-            rsync_output="$(echo "$PASSWORD" | run rsync --password-file - "$DESTUSER@$DESTHOSTFQ::$DESTDIR/")" || fatal "rsync failed"
-            local prev="$(echo "$rsync_output" |
-                          sed -n -e "/-$DATE-/d;s/^.* \($SRCHOST-$DATEREXP-$SRCLABEL\)\$/\1/p" |
-                          sort -r |
-                          head -n 1)"
-            [[ -n $prev ]] && LINK_DEST="$prev"
+            if [[ -z $rsync_output ]]; then
+                rsync_output=$(runalways rsync --password-file - "$DESTUSER@$DESTHOSTFQ::$DESTDIR/" <<<"$PASSWORD") || fatal "rsync failed"
+                [[ -z $rsync_output ]] && rsync_output='empty'
+            fi
+            LINK_DEST=$(sed -n -e "/-$DATE-/d;s/^.* \($SRCHOST-$DATEREXP-$SRCLABEL\)\$/\1/p" <<<"$rsync_output" |
+                         sort -r |
+                         head -n 1)
         fi
 
-        SRCPATHS+=("$SRCUSER $SRCHOST $SRCHOSTFQ $SRCLABEL ${LINK_DEST:--} $SRCPATH")
+        SOURCES+=("$SRCUSER" "$SRCHOST" "$SRCHOSTFQ" "$SRCLABEL" "$LINK_DEST" "$SRCPATH")
     done
 
-    local line
-    for line in "${SRCPATHS[@]}"; do
-	set -- $line
-	[[ $# -eq 6 ]] || fatal "Bug: \$#=$# \$line=$line"
-        SRCUSER="$1"
-	SRCHOST="$2"
-	SRCHOSTFQ="$3"
-	SRCLABEL="$4"
-	LINK_DEST="$5"
-	SRCPATH="$6"
+    set -- "${SOURCES[@]}"
+    while [[ $# -ne 0 ]]; do
+        [[ $# -ge 6 ]] || fatal "Bug: SOURCES only has $# elements left"
+        local SRCUSER=$1
+        local SRCHOST=$2
+        local SRCHOSTFQ=$3
+        local SRCLABEL=$4
+        local LINK_DEST=$5
+        local SRCPATH=$6
+        shift 6
         #echo "SRCUSER=$SRCUSER SRCHOST=$SRCHOST SRCHOSTFQ=$SRCHOSTFQ SRCLABEL=$SRCLABEL LINK_DEST=$LINK_DEST SRCPATH=$SRCPATH"
 
         local src
         local dst
-        local opts
+        local -a opts
 
         opts=()
         if $OPT_DRY_RUN; then
             opts+=("--dry-run")
         fi
 
-        src="$SRCPATH"
+        src=$SRCPATH
         if [[ $SRCHOSTFQ != $LOCAL_HOST_FQ ]]; then
-            src="$SRCUSER@$SRCHOSTFQ::$src"
+            src=$SRCUSER@$SRCHOSTFQ::$src
         fi
 
-        dst="$DESTDIR/$SRCHOST-$DATE-$SRCLABEL"
+        dst=$DESTDIR/$SRCHOST-$DATE-$SRCLABEL
         if [[ $DESTHOSTFQ != $LOCAL_HOST_FQ ]]; then
-            dst="$DESTUSER@$DESTHOSTFQ::$dst"
+            dst=$DESTUSER@$DESTHOSTFQ::$dst
             opts+=("--password-file" "-")
         fi
 
-        if [[ -n $LINK_DEST && $LINK_DEST != - ]]; then
+        if [[ $LINK_DEST ]]; then
             opts+=("--link-dest=../$LINK_DEST/")
         fi
 
-        if ! echo "$PASSWORD" |
-             run rsync --verbose --human-readable \
+        if ! run rsync --verbose --human-readable \
                 --one-file-system --archive --hard-links --inplace --delete \
                 --exclude '/lost+found' --delete-excluded \
                 --filter="dir-merge,- .rsync-backup-exclude" \
                 "${opts[@]}" "${OPTS_RSYNC[@]}" "$src/" "$dst/" \
-                2>"$ERR"
+                2>"$ERR" <<<"$PASSWORD"
         then
             rsync_stat=$?
             echo "exit status $rsync_stat"
@@ -155,33 +154,50 @@ main() {
 }
 
 parse_rsync_endpoint() {
-    local -n __user="${1}USER"
-    local -n __hostfq="${1}HOSTFQ"
-    local -n __host="${1}HOST"
-    local -n __dir="${1}DIR"
-    case "$2" in
+    local -n __user=${1}USER
+    local -n __hostfq=${1}HOSTFQ
+    local -n __host=${1}HOST
+    local -n __dir=${1}DIR
+    case $2 in
     ?*:*)
-        __dir="${2#*:}"
-        __user="$LOGNAME"
-        __host="${2%%:*}"
-        case "$__host" in
-        *@*) __user="${__host%%@*}"; __host="${__host#*@}";;
+        __dir=${2#*:}
+        __user=$LOGNAME
+        __host=${2%%:*}
+        case $__host in
+        *@*) __user=${__host%%@*}; __host=${__host#*@};;
         esac
-        __hostfq="$(fqdn "$__host")" || fatal "cannot resolve host: $__host"
+        __hostfq=$(fqdn "$__host") || fatal "cannot resolve host: $__host"
         ;;
     *)
-        __user="$LOGNAME"
-        __hostfq="$LOCAL_HOST_FQ"
-        __host="${__hostfq%%.*}"
-        __dir="$2"
+        __user=$LOGNAME
+        __hostfq=$LOCAL_HOST_FQ
+        __host=${__hostfq%%.*}
+        __dir=$2
         ;;
     esac
 }
 
+fqdn()
+{
+    if result=$(/bin/ping -c 1 -w 1 "$1"); then
+        case $result in
+        "PING "*" ("[0-9]*)
+            result=${result#PING }
+            result=${result%%[ (]*}
+            echo "$result"
+            return 0
+            ;;
+        esac
+    fi
+    return 1
+}
+
+exec 101>&1 102>&2
+
 fatal() {
-    echo "${0##*/}: $1" >&2
+    echo "${0##*/}: $1" >&102
     shift
-    for arg; do echo "$arg" >&2; done
+    for arg; do echo "$arg" >&102; done
     exit 1
 }
 
@@ -189,35 +205,22 @@ fatal_usage() {
     fatal "$1" "See \`${0##*/} --help' for more information."
 }
 
-exec 5>&1
+runalways() {
+    $OPT_ECHO && log "$@"
+    "$@"
+}
 
-run()
-{
-    if $OPT_ECHO; then
-        echo -n + >&5
-        printf ' %q' "$@" >&5
-        echo >&5
-    fi
-    if $OPT_TEST; then
-        :
-    else
+run() {
+    $OPT_ECHO && log "$@"
+    if ! $OPT_TEST; then
         "$@"
     fi
 }
 
-fqdn()
-{
-    if result=$(/bin/ping -c 1 -w 1 "$1"); then
-        case "$result" in
-        "PING "*" ("[0-9]*)
-            result="${result#PING }"
-            result="${result%%[ (]*}"
-            echo "$result"
-            return 0
-            ;;
-        esac
-    fi
-    return 1
+log() {
+    echo -n + >&101
+    printf ' %q' "$@" >&101
+    echo >&101
 }
 
 main "$@"
